Vagrant.configure("2") do |config|

  # web01 - Ubuntu 20.04
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.14"

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  # web02 - Ubuntu 20.04
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/focal64"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.56.15"

    web02.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  # db01 - CentOS 7
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.16"

    db01.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end

    # Provision MariaDB on db01
    db01.vm.provision "shell", inline: <<-SHELL
      yum update -y
      yum install -y mariadb-server wget unzip zip vim
      systemctl start mariadb
      systemctl enable mariadb
    SHELL
  end

end
