Vagrant.configure("2") do |config|
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.network "private_network", ip: "192.168.40.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = 1024
      vb.cpus = 2
    end
    web01.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y apache2 wget unzip openssh-server

      systemctl enable apache2
      systemctl start apache2

      systemctl enable ssh
      systemctl start ssh

      cd /tmp/
      wget https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip
      unzip -o 2119_gymso_fitness.zip
      cp -r 2119_gymso_fitness/* /var/www/html/
      chown -R www-data:www-data /var/www/html/
      systemctl restart apache2
    SHELL
  end

  # db01 in centos07
  config.vm.define "db01" do |db01|
    db01.vm.box = "ubuntu/jammy64"
    db01.vm.network "private_network", ip: "192.168.40.12"
    db01.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = 1024
      vb.cpus = 2
    end
    db01.vm.provision "shell", inline: <<-SHELL
        echo "Waiting for SSH and network..."
        sleep 10
        apt-get update -y
        apt-get install mariadb-server -y
        systemctl start mariadb
        systemctl enable mariadb
        mysql -u root -e "CREATE DATABASE gym;"
        mysql -u root -e "GRANT ALL PRIVILEGES ON gym.* TO 'gymuser'@'%' IDENTIFIED BY 'admin123';"
        mysql -u root -e "FLUSH PRIVILEGES;"
        SHELL
    end
end
